name: ml_pipeline_x86_64
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - alembic=1.8.1
  - appdirs=1.4.4
  - asn1crypto=1.5.1
  - attrs=22.1.0
  - autopage=0.5.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bcrypt=3.2.2
  - blas=1.0
  - blinker=1.4
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.9.24
  - captum=0.5.0
  - certifi=2022.9.24
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.1.3
  - cliff=3.10.1
  - cloudpickle=2.0.0
  - cmaes=0.8.2
  - cmd2=2.4.2
  - colorlog=6.7.0
  - configparser=5.3.0
  - cryptography=37.0.1
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - cytoolz=0.11.0
  - daal4py=2021.6.0
  - dal=2021.6.0
  - dask-core=2021.10.0
  - databricks-cli=0.17.3
  - debugpy=1.5.1
  - decorator=5.1.1
  - docker-py=5.0.3
  - docker-pycreds=0.4.0
  - entrypoints=0.4
  - ffmpeg=4.3
  - fftw=3.3.9
  - flask=2.2.2
  - fonttools=4.25.0
  - freetype=2.11.0
  - fsspec=2022.7.1
  - giflib=5.2.1
  - gitdb=4.0.9
  - gitpython=3.1.27
  - gmp=6.2.1
  - gnutls=3.6.15
  - greenlet=1.1.2
  - gunicorn=20.1.0
  - idna=3.3
  - imageio=2.19.3
  - importlib-metadata=4.11.4
  - importlib_metadata=4.11.4
  - importlib_resources=5.9.0
  - intel-openmp=2021.4.0
  - ipykernel=6.15.2
  - ipython=7.31.1
  - itsdangerous=2.1.2
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.1.0
  - jpeg=9e
  - jupyter_client=7.3.5
  - jupyter_core=4.10.0
  - keyutils=1.6.1
  - kiwisolver=1.4.2
  - krb5=1.19.3
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libpng=1.6.37
  - libpq=13.3
  - libprotobuf=3.18.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - locket=1.0.0
  - lz4-c=1.9.3
  - mako=1.2.3
  - markupsafe=2.1.1
  - matplotlib-base=3.5.2
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mlflow=1.29.0
  - mpi=1.0
  - mpich=3.3.2
  - munkres=1.1.4
  - natsort=8.2.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - nettle=3.7.3
  - networkx=2.6.3
  - numexpr=2.8.3
  - numpy=1.21.5
  - numpy-base=1.21.5
  - oauthlib=3.2.1
  - openh264=2.1.1
  - openssl=1.1.1o
  - optuna=3.0.2
  - packaging=21.3
  - pandas=1.3.5
  - paramiko=2.11.0
  - parso=0.8.3
  - partd=1.2.0
  - pbr=5.10.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.1.2
  - prettytable=3.4.1
  - prometheus_client=0.14.1
  - prometheus_flask_exporter=0.20.3
  - prompt-toolkit=3.0.20
  - protobuf=3.18.0
  - psutil=5.9.0
  - psycopg2=2.9.2
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pygments=2.11.2
  - pyjwt=2.5.0
  - pynacl=1.5.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyperclip=1.8.2
  - pysftp=0.2.9
  - pysocks=1.7.1
  - python=3.7.10
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - pytz=2022.1
  - pywavelets=1.3.0
  - pyyaml=6.0
  - pyzmq=23.2.0
  - querystring_parser=1.2.4
  - readline=8.1.2
  - requests=2.28.1
  - scikit-image=0.19.2
  - scikit-learn=1.0.2
  - scikit-learn-intelex=2021.6.0
  - scipy=1.7.3
  - setuptools=63.4.1
  - six=1.16.0
  - smmap=3.0.5
  - sqlalchemy=1.4.36
  - sqlite=3.39.2
  - sqlparse=0.4.3
  - stevedore=3.5.0
  - tabulate=0.8.10
  - tbb=2021.5.0
  - threadpoolctl=2.2.0
  - tifffile=2020.10.1
  - tk=8.6.12
  - toolz=0.11.2
  - torchaudio=0.12.1
  - torchmetrics=0.10.0
  - torchvision=0.13.1
  - tornado=6.2
  - tqdm=4.64.0
  - traitlets=5.1.1
  - typing_extensions=4.3.0
  - urllib3=1.26.11
  - wcwidth=0.2.5
  - websocket-client=1.4.1
  - werkzeug=2.2.2
  - wheel=0.37.1
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.8.1
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - attrdict==2.0.1
    - opencv-contrib-python==4.6.0.66
    - torchsampler==0.1.2

